version:          "3"
services:
  db:
    image:        mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
  app:
    image:        k2levin/php-laravel:misc
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    environment:
      - TZ=Asia/Singapore
    volumes:
      - "$PWD/:/var/www/app/mysqldump2s3/"
